# Generated by Django 4.2.20 on 2025-04-08 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTitle',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('beginners', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTitleTypeNexus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursetitle')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateTimeField(auto_now_add=True)),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursetitle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('details', models.TextField()),
                ('course_titles', models.ManyToManyField(through='main.CourseTitleTypeNexus', to='main.coursetitle')),
            ],
        ),
        migrations.AddField(
            model_name='coursetitletypenexus',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursetype'),
        ),
        migrations.AddField(
            model_name='coursetitle',
            name='course_types',
            field=models.ManyToManyField(through='main.CourseTitleTypeNexus', to='main.coursetype'),
        ),
    ]
