# Generated by Django 4.2.20 on 2025-04-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_coursetype_course_titles_coursetitle_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner: A1'), ('A2', 'Elementary: A2'), ('B1', 'Intermediate: B1'), ('B2', 'High Intermediate: B2'), ('C1', 'Advanced: C1'), ('C2', 'Proficient: C2')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
